 <!--Boton de Agregar-->
<button class="btn btn-labeled btn-success btn-sm" data-toggle="modal" data-target="#agregar_h" aria-expanded="false" aria-controls="agregar_h">
<span class="btn-label">
    <span class="glyphicon glyphicon-plus"></span>
</span>
<strong>Agregar Herramienta</strong>
</button>
 <!--Menu de Agregar-->
<div id="agregar_h" class="modal" tabindex="-1" role="dialog" aria-labelledby="AgregarHerramienta">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="header-add">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h2 class="modal-title text-center" id="title-agregarH"><strong>Agregar Herramienta</strong></h2>
            </div>
            <div class="modal-body bg-success">
                <?= Form::open("herramientas/crear","POST",'onsubmit="return valida_herramienta()"'); ?>
                    <div class="form-group" id="h_nombre">
                        <?= Form::label("Nombre: ", "herramientas.nombre", 'class="control-label"' ); ?>
                        <?= Form::text("herramientas.nombre", 'class="form-control input-sm"' ); ?>
                    </div>
                    <div class="form-group" id="h_num">
                        <?= Form::label("Cantidad: ", "herramientas.num"); ?>
                        <?= Form::input('number','herramientas.num', 'class="form-control input-sm"'); ?>
                    </div>
                    <div class="form-group" id="h_serial">
                        <?= Form::label("Serial de la Herramienta: ", "herramientas.serial"); ?>
                        <?= Form::text("herramientas.serial", 'class="form-control input-sm" data-mask="wwwwwwww"'); ?>
                    </div>
                    <div class="form-group" id="h_status">
                        <?= Form::label("Estado de las Herramientas:　", "herramientas.status"); ?>
                        <?php $status_h = array( 'Seleccione', 'Disponible' , 'Dañado' , 'Prestado', ' Otro (No disponible) ' ); ?>
                        <?= Form::select("herramientas.status",$status_h, 'class="form-control input-sm"', 'Seleccione'); ?>
                    </div>
                    <div class="form-group text-center">
                        <button class="btn btn-success btn-sm btn-labeled" type="submit">Enviar
                            <span class="btn-label btn-label-right">
                            <span class="glyphicon glyphicon-send"></span>
                            </span>
                        </button>
                    </div>
            </div>   
         <?= Form::close(); ?>
        </div>
    </div>   
</div>

