 <!--Boton de Editar-->
<button class="btn btn-labeled btn-purple btn-sm" data-toggle="modal" data-target="#editar_h-<?= $id_h ?>" aria-expanded="false" aria-controls="editar_h-<?= $id_h ?>"><span class="btn-label"><span class="glyphicon glyphicon-edit"></span></span> Editar </button>
 <!--Menu de Editar-->
 <div id="editar_h-<?= $id_h ?>" class="modal" tabindex="-1" role="dialog" aria-labelledby="AgregarHerramienta">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="header-eh">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h2 class="modal-title text-center"><strong>Editar Herramienta</strong></h2>
            </div>
            <div class="modal-body bg-info">
                <?= Form::open("herramientas/editar"); ?>
                    <?= Form::hidden("herramientas.id", NULL, $id_h); ?>
                    <div class="form-group">
                        <?= Form::label("Nombre: ", "herramientas.nombre", 'class="control-label"' ); ?>
                        <?= Form::text("herramientas.nombre", 'class="form-control input-sm"', $nombre ); ?>
                    </div>
                    <div class="form-group">
                        <?= Form::label("Cantidad: ", "herramientas.num"); ?>
                        <?= Form::input('number','herramientas.num', 'class="form-control input-sm"', $cantidad ); ?>
                    </div>
                    <div class="form-group">
                        <?= Form::label("Serial de la Herramienta: ", "herramientas.serial"); ?>
                        <?= Form::text("herramientas.serial", 'class="form-control input-sm" data-mask="wwwwwwww"', $serial); ?>
                    </div>
                    <div class="form-group">
                        <?= Form::label("Estado de las Herramientas:　", "herramientas.status"); ?>
                        <?php $status_h = array( 'Seleccione', 'Disponible' , 'Dañado' , 'Prestado', ' Otro (No disponible) ' ); ?>
                        <?php if($cantidad==0): ?>
                        <?= Form::select("herramientas.status",$status_h, 'class="form-control input-sm"', 4 ); ?>
                        <?php else: ?>
                        <?= Form::select("herramientas.status",$status_h, 'class="form-control input-sm"', $num_status ); ?>
                        <?php endif; ?>
                    </div>
                    <div class="form-group text-center">
                        <button class="btn btn-info btn-sm btn-labeled" type="submit">Enviar
                            <span class="btn-label btn-label-right">
                            <span class="glyphicon glyphicon-send"></span>
                            </span>
                        </button>
                    </div>
                 <?= Form::close(); ?>
            </div>   
        </div>
    </div>   
</div>

