 <!--Boton de Editar-->
<button class="btn btn-labeled btn-purple btn-sm" data-toggle="modal" data-target="#editar_m-<?= $id_m ?>" aria-expanded="false" aria-controls="editar_m-<?= $id_m ?>"><span class="btn-label"><span class="glyphicon glyphicon-edit"></span></span> Editar </button>
 <!--Menu de Editar-->
 <div id="editar_m-<?= $id_m ?>" class="modal" tabindex="-1" role="dialog" aria-labelledby="EditarMaterial">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header" id="header-edit">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h2 class="modal-title text-center"><strong>Editar Herramienta</strong></h2>
            </div>
            <div class="modal-body bg-info">
                <?= Form::open("materiales/editar", "POST", 'onsubmit="return editar_material()"'); ?>
                    <?= Form::hidden("editar.id", NULL, $id_m); ?>
                    <div class="form-group" id="e_nombre">
                        <?= Form::label("Nombre: ", "editar.nombre", 'class="control-label"' ); ?>
                        <?= Form::text("editar.nombre", 'class="form-control input-sm"', $nombre ); ?>
                    </div>
                    <div class="form-group" id="e_num">
                        <?= Form::label("Cantidad: ", "editar.num"); ?>
                        <?= Form::input('number','editar.num', 'class="form-control input-sm"', $cantidad ); ?>
                    </div>
                    <div class="form-group" id="e_status">
                        <?= Form::label("Estado del Material:　", "editar.status"); ?>
                        <?php $status_m = array( 'Seleccione', 'Disponible', 'No disponible' ); ?>
                        <?php if($cantidad==0): ?>
                        <?= Form::select("editar.status",$status_m, 'class="form-control input-sm"', 2 ); ?>
                        <?php else: ?>
                        <?= Form::select("editar.status",$status_m, 'class="form-control input-sm"', $num_status ); ?>
                        <?php endif; ?>
                    </div>
                    <div class="form-group text-center">
                        <button class="btn btn-info btn-sm btn-labeled" type="submit">Enviar
                            <span class="btn-label btn-label-right">
                            <span class="glyphicon glyphicon-send"></span>
                            </span>
                        </button>
                    </div>
                 <?= Form::close(); ?>
            </div>   
        </div>
    </div>   
</div>
