<!-- Boton de Eliminar -->
<button class="btn btn-labeled btn-danger btn-sm" data-toggle="modal" data-target="#borrar_h-<?= $id_h ?>" aria-expanded="false" aria-controls="borrar_h-<?= id_h ?>"> 
    <span class="btn-label">
        <span class="glyphicon glyphicon-remove"></span>
    </span> Eliminar </button>
<!-- Modal ha mostrar Antes de borrar -->
<div id="borrar_h-<?= $id_h ?>" class="modal" tabindex="-1" role="dialog" aria-labelledby="BorrarHerramienta">
  <div class="modal-dialog modal-sm" role="document">
           <div class="modal-content text-center">
             <div class="modal-header" style="background-color:maroon;color:white;">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h2 class="modal-title">¿Seguro?</h2>
                </div>
        <div class="modal-body">
                <?= Html::link("herramientas/borrar/$id_h", "Sí", 'class="btn btn-danger"'); ?>
                <button class="btn btn-default" data-dismiss="modal"> No</button>
            </div>
        </div>
    </div>
</div>
