<?php View::partial("menu",FALSE, array("activo" => 'doc',"login" => "user" ) ) ?>
<?php View::partial("responsive") ?>
<!--Contenido-->
    <div class="page-header text-center">
        <h1>Documentación</h1>
    </div>
        <div class="row text-center">
          <div class="col-md-4 col-md-offset-1">
              <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title"><strong>Manual de Usuario</strong></h2>
                </div>
                <div class="panel-body">
                    <p>Funcionamiento de la Interfaz para el Usuario</p>
                    <?= Html::link("files/Manual_de_Usuario_SDGH.pdf", 'Descargar <span class="btn-label btn-label-right"><i class="glyphicon glyphicon-arrow-down"></i></span>', 'class="btn btn-primary btn-labeled"' ); ?>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title"><strong>Manual de Sistema</strong></h2>
                </div>
                <div class="panel-body">
                    <p>Funcionamiento completo del Sistema</p>
                    <?= Html::link("files/Manual_de_Sistema_SDGH.pdf", 'Descargar <span class="btn-label btn-label-right"><i class="glyphicon glyphicon-arrow-down"></i></span>', 'class="btn btn-primary btn-labeled"' ); ?>
                </div>
            </div>
        </div>
    </div>
</div>
