<?php View::partial("menu", FALSE, array( "activo" => 'home', "login" => "user" )) ?>
<?php View::partial("responsive") ?>
<br>
<?php View::content() ?>
<div class="page-header text-center">
<h1><strong>Programa Nacional de Formación de Mecánica </strong></h1>
</div>
<br>
<div class="container-fluid">
<div class="row">
<?= Html::img("logon.png","logo", 'class="img-responsive col-sm-6"'); ?>
<h3 class="col-sm-6"><u><strong>Misión:</strong></u></h3>
<p class="text-justify col-sm-6">Formar ciudadanos y ciudadanas integrales con principios y valores éticos, humanísticos, ecológicos y  sensibilidad  social,  con  dominio  en  lo  científico  y  tecnológico  para  la  coordinación,  planeación, programación,  ejecución,  dirección,  control  y  supervisión  de  los recursos  humanos,  financieros  y materiales durante  la gestión profesional   de  los activos de  los sistemas productivos, con eficiencia  en beneficio de  toda  la sociedad y      la recomposición de  las  fuerzas sociales, mejorando  la calidad de  vida  de  las  comunidades,  ajustándose  a  la  transformación  derivada  de  la  innovación  en  el aprendizaje, en el marco del proyecto país contenido en la Constitución de la República Bolivariana de Venezuela.</p>
</div>
</div>
<h3><u><strong>Visión:</strong></u></h3>
<p class="text-justify">Ser  el  programa  de  formación  académica  de  referencia  nacional  e  internacional,  en  el  área Mecánica, que contribuya con el desarrollo endógeno sustentable del país consolidando los diversos sectores  productivos  y  de  servicios,    a  través  de  la  formación  de  seres  humanos  integrales,  con valores y principios de la sociedad socialista del siglo XXI, ajustándose a la transformación derivada de la innovación en el aprendizaje, en el marco del proyecto país en procura de la suprema felicidad social.</p>
<h3><u><strong>Programa:</strong></u></h3>
<p class="text-justify">El PNF en Mecánica por  su  vinculación  con  los planes específicos  de  la  nación  y  las  políticas de todos  los entes gubernamentales y no gubernamentales, con el sector productivo y de servicios en general, como ejemplo  tenemos    los proyectos que  la  industria   petroquímica va a desarrollar en el periodo 2008 – 2013; el aumento de capacidad de producción previsto en PEQUIVEN, los planes de inversión  de  PDVSA  e  industrias  básicas  de  Guayana,  las  inversiones  previstas  en    el  área  de generación  eléctrica,  el  plan  ferroviario  nacional,  y  la  diversidad  de  planes  de  desarrollo  en  la industria  del  sector  público  y  privado;  con  lo  cual  se  convertiría  a  Venezuela  en  una  potencia industrial a nivel mundial que sirva de base para impulsar su desarrollo científico y tecnológico, a fin de contribuir a la transformación del modelo productivo nacional en un modelo socialista.
</p>
<br>
<br>
<br>
