<?php View::partial("menu",FALSE, array("activo2" => "active" ) ) ?>
<?php View::partial("responsive") ?>
<!--Contenido-->
    <div class="page-header text-center">
        <h1>Documentación</h1>
    </div>
        <div class="row text-center">
          <div class="col-md-4 col-md-offset-1">
              <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title"><strong>Manual de Usuario</strong></h2>
                </div>
                <div class="panel-body">
                    <p>Aqui va alguna descripcion</p>
                    <a href="#" class="btn btn-primary btn-labeled"> Descargar <span class="btn-label btn-label-right"><i class="glyphicon glyphicon-arrow-down"></i></span></a>
                </div>
            </div>
        </div>
        <div class="col-md-4 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title"><strong>Manual del Administrador</strong></h2>
                </div>
                <div class="panel-body">
                    <p>Aqui va alguna descripcion</p>
                    <a href="#" class="btn btn-primary btn-labeled"> Descargar <span class="btn-label btn-label-right"><i class="glyphicon glyphicon-arrow-down"></i></span></a>
                </div>
            </div>
        </div>
    </div>
</div>
