<?php View::partial("menu", FALSE, array( "activo3" => "active" )) ?>
<?php View::partial("responsive") ?>
<!--Encabezado de la pagina -->
<div class="page-header text-center">
    <h1>Listado de Herramientas</h1>
</div>
<div class="row">
    <!--Buscador de herramientas/materiales-->
    <div id="herramientas" class="col-xs-12 col-md-offset-1">
        <div class="input-group col-xs-6 col-xs-offset-3 col-md-4 col-md-offset-7">
        <input type="text" class="search form-control input-sm" placeholder="Buscar...">
        <div class="input-group-btn">
            <button class="btn btn-info btn-sm"><span class="glyphicon glyphicon-search"></span></button>
        </div>
    </div>
    <br>
    <!--Boton de Agregar-->
    <button class="btn btn-labeled btn-success btn-sm" data-toggle="collapse" data-target="#agregar_h" aria-expanded="false" aria-controls="agregar_h"><span class="btn-label"><span class="glyphicon glyphicon-plus"></span></span> <strong>Agregar Herramienta</strong></button>
    <button class="sort btn btn-default btn-sm" data-sort="nombre"> <span class="glyphicon glyphicon-sort"></span> Ordenar por nombre</button>
    <button class="sort btn btn-default btn-sm" data-sort="disponibilidad"> <span class="glyphicon glyphicon-sort"></span> Ordenar por Estado</button>
     <!--Menu de Agregar-->
    <div id="agregar_h" class="collapse">
        <div class="row">
            <form action="" class="bg-success">
                <div class="form-group col-md-6">
                    <label for="nom_h" class="control-label">Nombre: </label>
                    <input type="text" class="form-control input-sm" id="nom_h">
                </div>
                <div class="clearfix"></div>
                <div class="form-group col-md-6">
                    <label for="cantidad">Cantidad: </label>
                    <input type="number" class="form-control input-sm" id="cantidad">
                </div>
                <div class="clearfix"></div>
                <div class="form-group col-md-6">
                    <label for="serial">Serial de la Herramienta: </label>
                    <input type="text" class="form-control input-sm" data-mask="wwwwww" id="serial">
                </div>
                <div class="clearfix"></div>
                <div class="form-group col-md-6">
                    <label for="estado"> Estado de la Herramienta: </label>
                    <select id="estado" name="estado_h" class="form-control input-sm">
                        <option value="0">Excelente estado</option>
                        <option value="1">Reportar herramienta como dañada</option>
                        <option value="2">Anunciar que la herramienta fue dada a otro ente</option>
                    </select>
                </div>
                <div class="clearfix"></div>
                <div class="form-group col-md-6 text-center">
                    <button class="btn btn-success btn-sm btn-labeled">Enviar<span class="btn-label btn-label-right"><span class="glyphicon glyphicon-send"></span></span></button></div>
            </form>
        </div>
    </div>
<br>
<br>
    <div class="table-responsive">
         <table class="table">
            <thead>
                <!-- Titulo de la tabla-->
                <tr>
                <th>Nombre</th>
                <th>Cantidad</th>
                <th>Estado</th>
                <th>Serial</th>
                <th></th>
                </tr>
            </thead>        
            <tbody class="list">
<!-- Contenido de la tabla (dinámico)-->
<?php foreach ($herramienta as $item) : ?>
            <tr>
                <td class="nombre"> <?= $item->nombre ?></td>
                <td class="cantidad"> <span class="badge"><?= $item->num ?></span></td>
<?php //Estados de la herramienta
             if($item->num==0){
                echo '<td class="disponibilidad"> <span class="label label-danger">No disponible </span></td>';
// 1 = Disponible
             }else if($item->status==1){
                echo '<td class="disponibilidad"> <span class="label label-success">Disponible </span></td>';
// 2 = Dañado
             }else if($item->status==2){
                echo '<td class="disponibilidad"> <span class="label label-warning">Dañado</span></td>';
// 3 = Prestada
             }else if($item->status==3){
                echo '<td class="disponibilidad"> <span class="label label-info">Prestado</span></td>';
             }
?>
                <td> <span style="color:navy;">#</span><em><?= $item->serial ?></em> </td>
                <td> <button id="btn-editar-<?= $item->serial ?>" class="btn btn-labeled btn-purple btn-sm"><span class="btn-label"><span class="glyphicon glyphicon-edit"></span></span> Editar </button>
                <button id="btn-borrar-<?= $item->serial ?>" class="btn btn-labeled btn-danger btn-sm"> <span class="btn-label"><span class="glyphicon glyphicon-remove"></span></span> Eliminar </button>
                </td>
            </tr>
<?php endforeach; ?>
            </tbody>
        </table>
         <!--Paginacion dinamica con JS -->
            <div class="text-center"><ul class="pagination pagination-sm"></ul></div> 
    </div>

</div>
