<?php View::partial("menu", FALSE, array( "activo3" => "active" )) ?>
<?php View::partial("responsive") ?>
<!--Encabezado de la pagina -->
<div class="page-header text-center">
    <h1>Listado de Herramientas</h1>
</div>
<div class="row">
    <!--Buscador de herramientas/materiales-->
    <div id="herramientas" class="col-xs-12 col-md-offset-1">
        <div class="input-group col-xs-6 col-xs-offset-3 col-md-4 col-md-offset-7">
        <input type="text" class="search form-control input-sm" placeholder="Buscar...">
        <div class="input-group-btn">
            <button class="btn btn-info btn-sm"><span class="glyphicon glyphicon-search"></span></button>
        </div>
    </div>
    <br>
<?php View::partial("modals/agregar_herramienta") ?>
    <button class="sort btn btn-default btn-sm" data-sort="nombre"> <span class="glyphicon glyphicon-sort"></span> Ordenar por nombre</button>
    <button class="sort btn btn-default btn-sm" data-sort="disponibilidad"> <span class="glyphicon glyphicon-sort"></span> Ordenar por Estado</button>
<br>
<br>
    <div class="table-responsive">
         <table class="table">
            <thead>
                <!-- Titulo de la tabla-->
                <tr>
                <th>Nombre</th>
                <th>Cantidad</th>
                <th>Estado</th>
                <th>Serial</th>
                <th></th>
                </tr>
            </thead>        
            <tbody class="list">
<!-- Contenido de la tabla (dinámico)-->
<?php foreach ($herramienta as $item) : ?>
            <tr>
                <td class="nombre"> <?= $item->nombre ?></td>
                <td class="cantidad"> <span class="badge"><?= $item->num ?></span></td>
                <!-- Estados de la herramienta -->
                <?php if($item->num==0) : ?> 
                    <td class="disponibilidad"> <span class="label label-danger">No disponible </span></td>
                 <!-- 1 = Disponible -->
                <?php elseif($item->status==1): ?>
                    <td class="disponibilidad"> <span class="label label-success">Disponible </span></td>
                 <!-- 2 = Dañado -->
                <?php elseif($item->status==2): ?>
                    <td class="disponibilidad"> <span class="label label-warning">Dañado</span></td>
                 <!-- 3 = Prestada -->
                <?php elseif($item->status==3): ?>
                    <td class="disponibilidad"> <span class="label label-info">Prestado</span></td>
                <!-- Cualquier otro estado es que no esta disponible -->
                <?php else: ?>
                    <td class="disponibilidad"> <span class="label label-danger">No disponible </span></td>
                <?php endif; ?>
                <td> <span style="color:navy;">#</span><em><?= $item->serial ?></em> </td>
                <td> <button id="btn-editar-<?= $item->serial ?>" class="btn btn-labeled btn-purple btn-sm"><span class="btn-label"><span class="glyphicon glyphicon-edit"></span></span> Editar </button>
                <button id="btn-borrar-<?= $item->serial ?>" class="btn btn-labeled btn-danger btn-sm"> <span class="btn-label"><span class="glyphicon glyphicon-remove"></span></span> Eliminar </button>
                </td>
            </tr>
<?php endforeach; ?>
            </tbody>
        </table>
         <!--Paginacion dinamica con JS -->
            <div class="text-center"><ul class="pagination pagination-sm"></ul></div> 
    </div>

</div>
