<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset=<?= APP_CHARSET ?> >
  <title>Sistema de Gestion de Herramientas</title>
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <?php Html::headLink('favicon.png', "rel='icon'") ?>
  <?= Html::includeHeadLinks() ?>
  <?php Tag::css('index') ?>
  <?php Tag::css('bootstrap.min') ?>
  <?= Html::includeCss() ?>
</head>
<body>
<div class="container">
    <?php View::content() ?>
</div>
<?= Tag::js('jquery.min') ?>
<?= Tag::js('notify.min') ?>
<?= Tag::js('bootstrap.min') ?>
<?= Tag::js('jasny-bootstrap.min') ?>
</body>
</html>
