<!DOCTYPE html>
<html lang="es">
 <head>
  <meta charset=<?= APP_CHARSET ?> >
  <title>Sistema de Gestion de Herramientas</title>
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <?php Html::headLink('favicon.png', "rel='icon'") ?>
  <?= Html::includeHeadLinks() ?>
  <?php Tag::css('index') ?>
  <?php Tag::css('base') ?>
  <?php Tag::css('bootstrap.min') ?>
  <?php Tag::css('jasny-bootstrap.min') ?>
  <?= Html::includeCss() ?>
</head>
<body>
<!-- Contenedor -->
<div class="main container-fluid">
    <div class="row">
        <?php View::content() ?>
    </div>
</div>
<?= Tag::js('jquery.min') ?>
<?= Tag::js('bootstrap.min') ?>
<?= Tag::js('jasny-bootstrap.min') ?>
<?= Tag::js('list.min') ?>
<?= Tag::js('list.pagination.min') ?>
<?= Tag::js('busqueda_herramientas') ?>
</body>
</html>
